x = var('x')
y = function('y',x)
de = -diff(y,x,2) + diff(y,x)
g = desolve(de,y)
var('_K1','_K2')
sol = solve([g(x=0)==1, gp(x=1) + g(x=1) == 0], _K1, _K2, solution_dict=True)
g = g.subs(sol[0])
p = plot(g,xmin=0,xmax=1,ymin=0,ymax=1)
data = np.loadtxt("/home/lindsayad/zapdos/problems/dg_advection_diffusion_robin.csv",delimiter=',')
moose = list_plot(data)
show(p+moose)