#!/usr/bin/python
#
# Read in tab separated Temperature data and generate 1D plot
#
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rc
rc('text', usetex=True)
#
arrowShrinkSize = 0.1
figureFontSize = 12
arrowWidth = 1
#
z, Temp = np.loadtxt('1D_temperature_along_axis.txt',unpack = True)
z_min, z_max = z.min(), z.max()
T_min, T_max = Temp.min(), Temp.max()
#
plt.plot(z,Temp, 'k-')
plt.xlabel('z (m)', fontsize = figureFontSize)
plt.ylabel('Temperature (K)', fontsize = figureFontSize)
plt.plot([0, 0],[290, 302], 'k--')
plt.annotate('Interface', xy=(0.0,301), xytext = (-0.003, 300), arrowprops=dict(facecolor='black',shrink=arrowShrinkSize, width = arrowWidth), fontsize = figureFontSize)
plt.text(0.004, 293, 'Gas', fontsize = figureFontSize)
plt.text(-0.003, 293, 'Liquid', fontsize = figureFontSize)
#
plt.savefig('1D_temperature_plot.eps',format='eps')
plt.show()
